backend:
  name: github
  repo: affimania/affimania 
  branch: main 

media_folder: "assets/img" 
public_folder: "/assets/img"

collections:
  - name: "deals"
    label: "Amazon Daily Deals"
    folder: "_deals" 
    create: true
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Current Price (â‚¹)", name: "price", widget: "number"}
      - {label: "Savings", name: "savings", widget: "string"}
      - {label: "Amazon Affiliate Link", name: "affiliate_link", widget: "string"}
      - {label: "Product Image URL", name: "image", widget: "string"}
